import type { MarketplaceItem } from "../types"

export const mockMarketplaceItems: MarketplaceItem[] = [
  {
    id: "1",
    name: "Premium Colombian Coffee Beans",
    category: "Coffee Beans",
    description: "Single-origin Colombian beans, medium roast, perfect for espresso",
    unit: "lbs",
    pricePerUnit: 15.5,
    availableQuantity: 200,
    minOrderQuantity: 10,
    sellerId: "admin2",
    sellerName: "Maria Rodriguez",
    sellerLocationId: "loc2",
    sellerLocationName: "Downtown Roastery",
    quality: "Premium",
    certifications: ["Organic", "Fair Trade"],
    productionDate: new Date("2024-01-20"),
    expiryDate: new Date("2024-07-20"),
    isActive: true,
    createdAt: new Date("2024-01-21"),
  },
  {
    id: "2",
    name: "House-Made Vanilla Syrup",
    category: "Syrups",
    description: "Artisanal vanilla syrup made with real vanilla beans",
    unit: "bottles",
    pricePerUnit: 8.75,
    availableQuantity: 50,
    minOrderQuantity: 5,
    sellerId: "admin3",
    sellerName: "David Kim",
    sellerLocationId: "loc3",
    sellerLocationName: "Westside Cafe",
    quality: "Premium",
    certifications: ["Natural"],
    productionDate: new Date("2024-01-18"),
    expiryDate: new Date("2024-04-18"),
    isActive: true,
    createdAt: new Date("2024-01-19"),
  },
  {
    id: "3",
    name: "Fresh Croissants",
    category: "Pastries",
    description: "Buttery, flaky croissants baked fresh daily",
    unit: "dozen",
    pricePerUnit: 18.0,
    availableQuantity: 20,
    minOrderQuantity: 2,
    sellerId: "admin4",
    sellerName: "Sophie Chen",
    sellerLocationId: "loc4",
    sellerLocationName: "Northside Bakery",
    quality: "Premium",
    certifications: ["Fresh Daily"],
    productionDate: new Date("2024-01-22"),
    expiryDate: new Date("2024-01-24"),
    isActive: true,
    createdAt: new Date("2024-01-22"),
  },
]
