import type { OrganizationNavigationSettings } from "../types"

export const mockNavigationSettings: OrganizationNavigationSettings[] = [
  {
    id: "nav-settings-1",
    organizationId: "1",
    ownerPermissions: [
      {
        id: "owner-dashboard-1",
        name: "Dashboard",
        href: "/dashboard",
        icon: "LayoutDashboard",
        enabled: true,
        role: "owner",
        organizationId: "1",
        createdAt: new Date("2023-01-20"),
        updatedAt: new Date("2023-01-20"),
      },
      {
        id: "owner-locations-1",
        name: "Locations",
        href: "/locations",
        icon: "MapPin",
        enabled: true,
        role: "owner",
        organizationId: "1",
        createdAt: new Date("2023-01-20"),
        updatedAt: new Date("2023-01-20"),
      },
      {
        id: "owner-reports-1",
        name: "Reports",
        href: "/reports",
        icon: "BarChart3",
        enabled: true,
        role: "owner",
        organizationId: "1",
        createdAt: new Date("2023-01-20"),
        updatedAt: new Date("2023-01-20"),
      },
      {
        id: "owner-analytics-1",
        name: "Analytics",
        href: "/analytics",
        icon: "TrendingUp",
        enabled: true,
        role: "owner",
        organizationId: "1",
        createdAt: new Date("2023-01-20"),
        updatedAt: new Date("2023-01-20"),
      },
      {
        id: "owner-catalog-1",
        name: "Catalog",
        href: "/catalog",
        icon: "Package",
        enabled: true,
        role: "owner",
        organizationId: "1",
        createdAt: new Date("2023-01-20"),
        updatedAt: new Date("2023-01-20"),
      },
      {
        id: "owner-staff-1",
        name: "Staff",
        href: "/staff",
        icon: "Users",
        enabled: true,
        role: "owner",
        organizationId: "1",
        createdAt: new Date("2023-01-20"),
        updatedAt: new Date("2023-01-20"),
      },
      {
        id: "owner-payroll-1",
        name: "Payroll",
        href: "/payroll",
        icon: "DollarSign",
        enabled: true,
        role: "owner",
        organizationId: "1",
        createdAt: new Date("2023-01-20"),
        updatedAt: new Date("2023-01-20"),
      },
      {
        id: "owner-scheduling-1",
        name: "Scheduling",
        href: "/scheduling",
        icon: "Calendar",
        enabled: true,
        role: "owner",
        organizationId: "1",
        createdAt: new Date("2023-01-20"),
        updatedAt: new Date("2023-01-20"),
      },
      {
        id: "owner-suppliers-1",
        name: "Suppliers",
        href: "/suppliers",
        icon: "Truck",
        enabled: true,
        role: "owner",
        organizationId: "1",
        createdAt: new Date("2023-01-20"),
        updatedAt: new Date("2023-01-20"),
      },
      {
        id: "owner-marketplace-1",
        name: "Marketplace",
        href: "/marketplace",
        icon: "Store",
        enabled: true,
        role: "owner",
        organizationId: "1",
        createdAt: new Date("2023-01-20"),
        updatedAt: new Date("2023-01-20"),
      },
      {
        id: "owner-procurement-1",
        name: "Procurement",
        href: "/procurement",
        icon: "ShoppingBag",
        enabled: true,
        role: "owner",
        organizationId: "1",
        createdAt: new Date("2023-01-20"),
        updatedAt: new Date("2023-01-20"),
      },
      {
        id: "owner-settings-1",
        name: "Settings",
        href: "/settings",
        icon: "Settings",
        enabled: true,
        role: "owner",
        organizationId: "1",
        createdAt: new Date("2023-01-20"),
        updatedAt: new Date("2023-01-20"),
      },
    ],
    cashierPermissions: [
      {
        id: "cashier-pos-1",
        name: "POS",
        href: "/pos",
        icon: "ShoppingCart",
        enabled: true,
        role: "cashier",
        organizationId: "1",
        createdAt: new Date("2023-01-20"),
        updatedAt: new Date("2023-01-20"),
      },
      {
        id: "cashier-kds-1",
        name: "KDS",
        href: "/kds",
        icon: "Monitor",
        enabled: true,
        role: "cashier",
        organizationId: "1",
        createdAt: new Date("2023-01-20"),
        updatedAt: new Date("2023-01-20"),
      },
      {
        id: "cashier-timeclock-1",
        name: "Time Clock",
        href: "/timeclock",
        icon: "Clock",
        enabled: true,
        role: "cashier",
        organizationId: "1",
        createdAt: new Date("2023-01-20"),
        updatedAt: new Date("2023-01-20"),
      },
      {
        id: "cashier-reports-1",
        name: "My Sales",
        href: "/reports",
        icon: "BarChart3",
        enabled: true,
        role: "cashier",
        organizationId: "1",
        createdAt: new Date("2023-01-20"),
        updatedAt: new Date("2023-01-20"),
      },
      {
        id: "cashier-transactions-1",
        name: "Transactions",
        href: "/transactions",
        icon: "Receipt",
        enabled: true,
        role: "cashier",
        organizationId: "1",
        createdAt: new Date("2023-01-20"),
        updatedAt: new Date("2023-01-20"),
      },
    ],
    createdAt: new Date("2023-01-20"),
    updatedAt: new Date("2023-01-20"),
  },
  {
    id: "nav-settings-2",
    organizationId: "2",
    ownerPermissions: [
      {
        id: "owner-dashboard-2",
        name: "Dashboard",
        href: "/dashboard",
        icon: "LayoutDashboard",
        enabled: true,
        role: "owner",
        organizationId: "2",
        createdAt: new Date("2023-03-25"),
        updatedAt: new Date("2023-03-25"),
      },
      {
        id: "owner-locations-2",
        name: "Locations",
        href: "/locations",
        icon: "MapPin",
        enabled: true,
        role: "owner",
        organizationId: "2",
        createdAt: new Date("2023-03-25"),
        updatedAt: new Date("2023-03-25"),
      },
      {
        id: "owner-reports-2",
        name: "Reports",
        href: "/reports",
        icon: "BarChart3",
        enabled: true,
        role: "owner",
        organizationId: "2",
        createdAt: new Date("2023-03-25"),
        updatedAt: new Date("2023-03-25"),
      },
      {
        id: "owner-analytics-2",
        name: "Analytics",
        href: "/analytics",
        icon: "TrendingUp",
        enabled: true,
        role: "owner",
        organizationId: "2",
        createdAt: new Date("2023-03-25"),
        updatedAt: new Date("2023-03-25"),
      },
      {
        id: "owner-catalog-2",
        name: "Catalog",
        href: "/catalog",
        icon: "Package",
        enabled: true,
        role: "owner",
        organizationId: "2",
        createdAt: new Date("2023-03-25"),
        updatedAt: new Date("2023-03-25"),
      },
      {
        id: "owner-staff-2",
        name: "Staff",
        href: "/staff",
        icon: "Users",
        enabled: true,
        role: "owner",
        organizationId: "2",
        createdAt: new Date("2023-03-25"),
        updatedAt: new Date("2023-03-25"),
      },
      {
        id: "owner-payroll-2",
        name: "Payroll",
        href: "/payroll",
        icon: "DollarSign",
        enabled: true,
        role: "owner",
        organizationId: "2",
        createdAt: new Date("2023-03-25"),
        updatedAt: new Date("2023-03-25"),
      },
      {
        id: "owner-scheduling-2",
        name: "Scheduling",
        href: "/scheduling",
        icon: "Calendar",
        enabled: true,
        role: "owner",
        organizationId: "2",
        createdAt: new Date("2023-03-25"),
        updatedAt: new Date("2023-03-25"),
      },
      {
        id: "owner-suppliers-2",
        name: "Suppliers",
        href: "/suppliers",
        icon: "Truck",
        enabled: true,
        role: "owner",
        organizationId: "2",
        createdAt: new Date("2023-03-25"),
        updatedAt: new Date("2023-03-25"),
      },
      {
        id: "owner-marketplace-2",
        name: "Marketplace",
        href: "/marketplace",
        icon: "Store",
        enabled: true,
        role: "owner",
        organizationId: "2",
        createdAt: new Date("2023-03-25"),
        updatedAt: new Date("2023-03-25"),
      },
      {
        id: "owner-procurement-2",
        name: "Procurement",
        href: "/procurement",
        icon: "ShoppingBag",
        enabled: true,
        role: "owner",
        organizationId: "2",
        createdAt: new Date("2023-03-25"),
        updatedAt: new Date("2023-03-25"),
      },
      {
        id: "owner-settings-2",
        name: "Settings",
        href: "/settings",
        icon: "Settings",
        enabled: true,
        role: "owner",
        organizationId: "2",
        createdAt: new Date("2023-03-25"),
        updatedAt: new Date("2023-03-25"),
      },
    ],
    cashierPermissions: [
      {
        id: "cashier-pos-2",
        name: "POS",
        href: "/pos",
        icon: "ShoppingCart",
        enabled: true,
        role: "cashier",
        organizationId: "2",
        createdAt: new Date("2023-03-25"),
        updatedAt: new Date("2023-03-25"),
      },
      {
        id: "cashier-kds-2",
        name: "KDS",
        href: "/kds",
        icon: "Monitor",
        enabled: true,
        role: "cashier",
        organizationId: "2",
        createdAt: new Date("2023-03-25"),
        updatedAt: new Date("2023-03-25"),
      },
      {
        id: "cashier-timeclock-2",
        name: "Time Clock",
        href: "/timeclock",
        icon: "Clock",
        enabled: true,
        role: "cashier",
        organizationId: "2",
        createdAt: new Date("2023-03-25"),
        updatedAt: new Date("2023-03-25"),
      },
      {
        id: "cashier-reports-2",
        name: "My Sales",
        href: "/reports",
        icon: "BarChart3",
        enabled: true,
        role: "cashier",
        organizationId: "2",
        createdAt: new Date("2023-03-25"),
        updatedAt: new Date("2023-03-25"),
      },
      {
        id: "cashier-transactions-2",
        name: "Transactions",
        href: "/transactions",
        icon: "Receipt",
        enabled: true,
        role: "cashier",
        organizationId: "2",
        createdAt: new Date("2023-03-25"),
        updatedAt: new Date("2023-03-25"),
      },
    ],
    createdAt: new Date("2023-03-25"),
    updatedAt: new Date("2023-03-25"),
  },
]
