import type { Product } from "../types"

export const mockProducts: Product[] = [
  // Brew & Bean Coffee Co. (Org 1) - Downtown Location (Location 1)
  {
    id: "1-1-1",
    name: "Espresso",
    category: "Coffee",
    basePrice: 2.5,
    organizationId: "1",
    locationId: "1",
    sizes: [
      { id: "s1", name: "Single", price: 2.5 },
      { id: "s2", name: "Double", price: 3.5 },
    ],
    modifiers: [
      { id: "m1", name: "Extra Shot", price: 0.75, category: "Coffee" },
      { id: "m2", name: "Decaf", price: 0, category: "Coffee" },
    ],
    available: true,
  },
  {
    id: "1-1-2",
    name: "Cappuccino",
    category: "Coffee",
    basePrice: 4.25,
    organizationId: "1",
    locationId: "1",
    sizes: [
      { id: "s3", name: "Small", price: 4.25 },
      { id: "s4", name: "Medium", price: 4.95 },
      { id: "s5", name: "Large", price: 5.65 },
    ],
    modifiers: [
      { id: "m1", name: "Extra Shot", price: 0.75, category: "Coffee" },
      { id: "m3", name: "Oat Milk", price: 0.65, category: "Milk" },
      { id: "m4", name: "Almond Milk", price: 0.65, category: "Milk" },
    ],
    available: true,
  },
  {
    id: "1-1-3",
    name: "Latte",
    category: "Coffee",
    basePrice: 4.75,
    organizationId: "1",
    locationId: "1",
    sizes: [
      { id: "s6", name: "Small", price: 4.75 },
      { id: "s7", name: "Medium", price: 5.45 },
      { id: "s8", name: "Large", price: 6.15 },
    ],
    modifiers: [
      { id: "m1", name: "Extra Shot", price: 0.75, category: "Coffee" },
      { id: "m3", name: "Oat Milk", price: 0.65, category: "Milk" },
      { id: "m5", name: "Vanilla Syrup", price: 0.5, category: "Syrup" },
    ],
    available: true,
  },
  {
    id: "1-2-1",
    name: "Espresso",
    category: "Coffee",
    basePrice: 2.75,
    organizationId: "1",
    locationId: "2",
    sizes: [
      { id: "s1", name: "Single", price: 2.75 },
      { id: "s2", name: "Double", price: 3.75 },
    ],
    modifiers: [
      { id: "m1", name: "Extra Shot", price: 0.75, category: "Coffee" },
      { id: "m2", name: "Decaf", price: 0, category: "Coffee" },
    ],
    available: true,
  },
  {
    id: "1-2-2",
    name: "Cappuccino",
    category: "Coffee",
    basePrice: 4.5,
    organizationId: "1",
    locationId: "2",
    sizes: [
      { id: "s3", name: "Small", price: 4.5 },
      { id: "s4", name: "Medium", price: 5.2 },
      { id: "s5", name: "Large", price: 5.9 },
    ],
    modifiers: [
      { id: "m1", name: "Extra Shot", price: 0.75, category: "Coffee" },
      { id: "m3", name: "Oat Milk", price: 0.65, category: "Milk" },
      { id: "m4", name: "Almond Milk", price: 0.65, category: "Milk" },
    ],
    available: true,
  },
  {
    id: "2-5-1",
    name: "House Blend",
    category: "Coffee",
    basePrice: 3.25,
    organizationId: "2",
    locationId: "5",
    sizes: [
      { id: "s9", name: "Small", price: 3.25 },
      { id: "s10", name: "Medium", price: 3.95 },
      { id: "s11", name: "Large", price: 4.65 },
    ],
    modifiers: [
      { id: "m6", name: "Extra Shot", price: 0.5, category: "Coffee" },
      { id: "m7", name: "Soy Milk", price: 0.5, category: "Milk" },
    ],
    available: true,
  },
  {
    id: "2-5-2",
    name: "Cold Brew",
    category: "Cold Drinks",
    basePrice: 3.75,
    organizationId: "2",
    locationId: "5",
    sizes: [
      { id: "s12", name: "Regular", price: 3.75 },
      { id: "s13", name: "Large", price: 4.45 },
    ],
    modifiers: [
      { id: "m8", name: "Vanilla Syrup", price: 0.5, category: "Syrup" },
      { id: "m9", name: "Caramel Syrup", price: 0.5, category: "Syrup" },
    ],
    available: true,
  },
  {
    id: "3-7-1",
    name: "Premium Americano",
    category: "Coffee",
    basePrice: 4.25,
    organizationId: "3",
    locationId: "7",
    sizes: [
      { id: "s14", name: "Small", price: 4.25 },
      { id: "s15", name: "Medium", price: 4.95 },
      { id: "s16", name: "Large", price: 5.65 },
    ],
    modifiers: [
      { id: "m10", name: "Extra Shot", price: 0.75, category: "Coffee" },
      { id: "m11", name: "Oat Milk", price: 0.65, category: "Milk" },
    ],
    available: true,
  },
  {
    id: "3-7-2",
    name: "Executive Latte",
    category: "Coffee",
    basePrice: 5.95,
    organizationId: "3",
    locationId: "7",
    sizes: [
      { id: "s17", name: "Small", price: 5.95 },
      { id: "s18", name: "Medium", price: 6.65 },
      { id: "s19", name: "Large", price: 7.35 },
    ],
    modifiers: [
      { id: "m12", name: "Premium Vanilla", price: 0.75, category: "Syrup" },
      { id: "m13", name: "Almond Milk", price: 0.65, category: "Milk" },
    ],
    available: true,
  },
  {
    id: "4-10-1",
    name: "Single Origin Ethiopian",
    category: "Coffee",
    basePrice: 6.25,
    organizationId: "4",
    locationId: "10",
    sizes: [
      { id: "s20", name: "Small", price: 6.25 },
      { id: "s21", name: "Medium", price: 6.95 },
      { id: "s22", name: "Large", price: 7.65 },
    ],
    modifiers: [
      { id: "m14", name: "Light Roast", price: 0, category: "Roast" },
      { id: "m15", name: "Medium Roast", price: 0, category: "Roast" },
      { id: "m16", name: "Dark Roast", price: 0, category: "Roast" },
    ],
    available: true,
  },
  {
    id: "4-10-2",
    name: "Artisan Cappuccino",
    category: "Coffee",
    basePrice: 5.75,
    organizationId: "4",
    locationId: "10",
    sizes: [
      { id: "s23", name: "Small", price: 5.75 },
      { id: "s24", name: "Medium", price: 6.45 },
      { id: "s25", name: "Large", price: 7.15 },
    ],
    modifiers: [
      { id: "m17", name: "House-made Oat Milk", price: 0.85, category: "Milk" },
      { id: "m18", name: "Lavender Syrup", price: 0.75, category: "Syrup" },
    ],
    available: true,
  },
]
