import type { User } from "../types"

export const mockUsers: User[] = [
  {
    id: "1",
    name: "Super Admin",
    email: "super@coffeeshop.com",
    role: "superuser",
    isActive: true,
    createdAt: new Date("2023-01-01"),
  },

  // Brew & Bean Coffee Co. (Org 1)
  {
    id: "2",
    name: "John Owner",
    email: "john@brewbean.com",
    role: "owner",
    organizationId: "1",
    isActive: true,
    createdAt: new Date("2023-01-15"),
  },
  {
    id: "3",
    name: "Jane Manager",
    email: "jane@brewbean.com",
    role: "admin",
    organizationId: "1",
    locationId: "1",
    isActive: true,
    createdAt: new Date("2023-02-01"),
  },
  {
    id: "4",
    name: "Mike Cashier",
    email: "mike@brewbean.com",
    role: "cashier",
    organizationId: "1",
    locationId: "1",
    isActive: true,
    createdAt: new Date("2023-02-15"),
  },
  {
    id: "5",
    name: "Sarah Admin",
    email: "sarah@brewbean.com",
    role: "admin",
    organizationId: "1",
    locationId: "2",
    isActive: true,
    createdAt: new Date("2023-03-01"),
  },
  {
    id: "6",
    name: "Tom Cashier",
    email: "tom@brewbean.com",
    role: "cashier",
    organizationId: "1",
    locationId: "2",
    isActive: true,
    createdAt: new Date("2023-03-15"),
  },
  {
    id: "7",
    name: "Lisa Cashier",
    email: "lisa@brewbean.com",
    role: "cashier",
    organizationId: "1",
    locationId: "1",
    isActive: true,
    createdAt: new Date("2023-04-01"),
  },
  {
    id: "8",
    name: "David Barista",
    email: "david@brewbean.com",
    role: "cashier",
    organizationId: "1",
    locationId: "3",
    isActive: true,
    createdAt: new Date("2023-04-15"),
  },

  // Morning Grind Coffee (Org 2)
  {
    id: "9",
    name: "Emma Wilson",
    email: "emma@morninggrind.com",
    role: "owner",
    organizationId: "2",
    isActive: true,
    createdAt: new Date("2023-03-20"),
  },
  {
    id: "12",
    name: "Alex Manager",
    email: "alex@morninggrind.com",
    role: "admin",
    organizationId: "2",
    locationId: "5",
    isActive: true,
    createdAt: new Date("2023-04-01"),
  },
  {
    id: "13",
    name: "Chris Cashier",
    email: "chris@morninggrind.com",
    role: "cashier",
    organizationId: "2",
    locationId: "5",
    isActive: true,
    createdAt: new Date("2023-04-15"),
  },
  {
    id: "14",
    name: "Maya Admin",
    email: "maya@morninggrind.com",
    role: "admin",
    organizationId: "2",
    locationId: "6",
    isActive: true,
    createdAt: new Date("2023-05-01"),
  },

  // Coffee Corner (Org 3)
  {
    id: "10",
    name: "Robert Johnson",
    email: "robert@coffeecorner.com",
    role: "owner",
    organizationId: "3",
    isActive: true,
    createdAt: new Date("2023-06-10"),
  },
  {
    id: "15",
    name: "Nina Manager",
    email: "nina@coffeecorner.com",
    role: "admin",
    organizationId: "3",
    locationId: "7",
    isActive: true,
    createdAt: new Date("2023-06-20"),
  },
  {
    id: "16",
    name: "Paul Cashier",
    email: "paul@coffeecorner.com",
    role: "cashier",
    organizationId: "3",
    locationId: "7",
    isActive: true,
    createdAt: new Date("2023-07-01"),
  },
  {
    id: "17",
    name: "Grace Admin",
    email: "grace@coffeecorner.com",
    role: "admin",
    organizationId: "3",
    locationId: "8",
    isActive: true,
    createdAt: new Date("2023-07-15"),
  },

  // Artisan Roasters (Org 4)
  {
    id: "11",
    name: "Maria Rodriguez",
    email: "maria@artisanroasters.com",
    role: "owner",
    organizationId: "4",
    isActive: true,
    createdAt: new Date("2023-08-05"),
  },
  {
    id: "18",
    name: "Carlos Manager",
    email: "carlos@artisanroasters.com",
    role: "admin",
    organizationId: "4",
    locationId: "10",
    isActive: true,
    createdAt: new Date("2023-08-15"),
  },
  {
    id: "19",
    name: "Sofia Cashier",
    email: "sofia@artisanroasters.com",
    role: "cashier",
    organizationId: "4",
    locationId: "10",
    isActive: true,
    createdAt: new Date("2023-09-01"),
  },
]
