import type { ThemeConfig } from "./types"

export const themePresets: ThemeConfig[] = [
  {
    id: "classic-coffee",
    name: "Classic Coffee",
    description: "Warm browns and creams for a traditional coffee shop feel",
    isDark: false,
    colors: {
      primary: "hsl(25, 47%, 45%)", // Coffee brown
      secondary: "hsl(35, 25%, 85%)", // Cream
      accent: "hsl(15, 65%, 55%)", // Warm orange
      background: "hsl(0, 0%, 100%)",
      foreground: "hsl(25, 15%, 15%)",
      muted: "hsl(35, 15%, 95%)",
      mutedForeground: "hsl(25, 8%, 45%)",
      card: "hsl(0, 0%, 100%)",
      cardForeground: "hsl(25, 15%, 15%)",
      border: "hsl(35, 15%, 85%)",
      input: "hsl(35, 15%, 95%)",
      ring: "hsl(25, 47%, 45%)",
      destructive: "hsl(0, 84%, 60%)",
      destructiveForeground: "hsl(0, 0%, 98%)",
      warning: "hsl(38, 92%, 50%)",
      warningForeground: "hsl(0, 0%, 98%)",
      success: "hsl(142, 76%, 36%)",
      successForeground: "hsl(0, 0%, 98%)",
    },
    typography: {
      fontFamily: "Inter, system-ui, sans-serif",
      headingFont: "Playfair Display, serif",
      fontSize: {
        xs: "0.75rem",
        sm: "0.875rem",
        base: "1rem",
        lg: "1.125rem",
        xl: "1.25rem",
        "2xl": "1.5rem",
        "3xl": "1.875rem",
        "4xl": "2.25rem",
      },
      fontWeight: {
        normal: "400",
        medium: "500",
        semibold: "600",
        bold: "700",
      },
    },
    spacing: {
      radius: "0.5rem",
      spacing: {
        xs: "0.25rem",
        sm: "0.5rem",
        md: "1rem",
        lg: "1.5rem",
        xl: "2rem",
        "2xl": "3rem",
      },
    },
  },
  {
    id: "modern-minimalist",
    name: "Modern Minimalist",
    description: "Clean lines and neutral tones for a contemporary look",
    isDark: false,
    colors: {
      primary: "hsl(220, 14%, 20%)", // Dark gray
      secondary: "hsl(220, 14%, 96%)", // Light gray
      accent: "hsl(142, 76%, 36%)", // Fresh green
      background: "hsl(0, 0%, 100%)",
      foreground: "hsl(220, 14%, 11%)",
      muted: "hsl(220, 14%, 96%)",
      mutedForeground: "hsl(220, 8%, 46%)",
      card: "hsl(0, 0%, 100%)",
      cardForeground: "hsl(220, 14%, 11%)",
      border: "hsl(220, 13%, 91%)",
      input: "hsl(220, 13%, 91%)",
      ring: "hsl(220, 14%, 20%)",
      destructive: "hsl(0, 84%, 60%)",
      destructiveForeground: "hsl(0, 0%, 98%)",
      warning: "hsl(38, 92%, 50%)",
      warningForeground: "hsl(0, 0%, 98%)",
      success: "hsl(142, 76%, 36%)",
      successForeground: "hsl(0, 0%, 98%)",
    },
    typography: {
      fontFamily: "Inter, system-ui, sans-serif",
      headingFont: "Inter, system-ui, sans-serif",
      fontSize: {
        xs: "0.75rem",
        sm: "0.875rem",
        base: "1rem",
        lg: "1.125rem",
        xl: "1.25rem",
        "2xl": "1.5rem",
        "3xl": "1.875rem",
        "4xl": "2.25rem",
      },
      fontWeight: {
        normal: "400",
        medium: "500",
        semibold: "600",
        bold: "700",
      },
    },
    spacing: {
      radius: "0.375rem",
      spacing: {
        xs: "0.25rem",
        sm: "0.5rem",
        md: "1rem",
        lg: "1.5rem",
        xl: "2rem",
        "2xl": "3rem",
      },
    },
  },
  {
    id: "artisan-dark",
    name: "Artisan Dark",
    description: "Rich dark theme with gold accents for premium coffee shops",
    isDark: true,
    colors: {
      primary: "hsl(45, 100%, 70%)", // Gold
      secondary: "hsl(25, 15%, 25%)", // Dark brown
      accent: "hsl(15, 85%, 65%)", // Copper
      background: "hsl(25, 15%, 8%)",
      foreground: "hsl(45, 25%, 90%)",
      muted: "hsl(25, 15%, 15%)",
      mutedForeground: "hsl(45, 8%, 65%)",
      card: "hsl(25, 15%, 12%)",
      cardForeground: "hsl(45, 25%, 90%)",
      border: "hsl(25, 15%, 20%)",
      input: "hsl(25, 15%, 15%)",
      ring: "hsl(45, 100%, 70%)",
      destructive: "hsl(0, 84%, 60%)",
      destructiveForeground: "hsl(0, 0%, 98%)",
      warning: "hsl(38, 92%, 50%)",
      warningForeground: "hsl(0, 0%, 98%)",
      success: "hsl(142, 76%, 36%)",
      successForeground: "hsl(0, 0%, 98%)",
    },
    typography: {
      fontFamily: "Inter, system-ui, sans-serif",
      headingFont: "Crimson Text, serif",
      fontSize: {
        xs: "0.75rem",
        sm: "0.875rem",
        base: "1rem",
        lg: "1.125rem",
        xl: "1.25rem",
        "2xl": "1.5rem",
        "3xl": "1.875rem",
        "4xl": "2.25rem",
      },
      fontWeight: {
        normal: "400",
        medium: "500",
        semibold: "600",
        bold: "700",
      },
    },
    spacing: {
      radius: "0.75rem",
      spacing: {
        xs: "0.25rem",
        sm: "0.5rem",
        md: "1rem",
        lg: "1.5rem",
        xl: "2rem",
        "2xl": "3rem",
      },
    },
  },
  {
    id: "vibrant-modern",
    name: "Vibrant Modern",
    description: "Bold colors and modern typography for trendy coffee shops",
    isDark: false,
    colors: {
      primary: "hsl(280, 100%, 70%)", // Vibrant purple
      secondary: "hsl(200, 100%, 95%)", // Light blue
      accent: "hsl(45, 100%, 60%)", // Bright yellow
      background: "hsl(0, 0%, 100%)",
      foreground: "hsl(280, 15%, 15%)",
      muted: "hsl(200, 25%, 96%)",
      mutedForeground: "hsl(280, 8%, 45%)",
      card: "hsl(0, 0%, 100%)",
      cardForeground: "hsl(280, 15%, 15%)",
      border: "hsl(200, 25%, 85%)",
      input: "hsl(200, 25%, 95%)",
      ring: "hsl(280, 100%, 70%)",
      destructive: "hsl(0, 84%, 60%)",
      destructiveForeground: "hsl(0, 0%, 98%)",
      warning: "hsl(38, 92%, 50%)",
      warningForeground: "hsl(0, 0%, 98%)",
      success: "hsl(142, 76%, 36%)",
      successForeground: "hsl(0, 0%, 98%)",
    },
    typography: {
      fontFamily: "Poppins, system-ui, sans-serif",
      headingFont: "Poppins, system-ui, sans-serif",
      fontSize: {
        xs: "0.75rem",
        sm: "0.875rem",
        base: "1rem",
        lg: "1.125rem",
        xl: "1.25rem",
        "2xl": "1.5rem",
        "3xl": "1.875rem",
        "4xl": "2.25rem",
      },
      fontWeight: {
        normal: "400",
        medium: "500",
        semibold: "600",
        bold: "700",
      },
    },
    spacing: {
      radius: "1rem",
      spacing: {
        xs: "0.25rem",
        sm: "0.5rem",
        md: "1rem",
        lg: "1.5rem",
        xl: "2rem",
        "2xl": "3rem",
      },
    },
  },
]
